export const GET_TOKEN = "GET_TOKEN";
export const GET_PLANET = "GET_PLANET";
export const GET_VEHICLE = "GET_VEHICLE";

export const INCREAMENT_VEHICLE_COUNT = "INCREAMENT_VEHICLE_COUNT";
export const DECREAMENT_VEHICLE_COUNT = "DECREAMENT_VEHICLE_COUNT";
export const MARK_PLANET_SELECTED = "MARK_PLANET_SELECTED";

export const UPDATE_JOURNEY = "UPDATE_JOURNEY";
export const VALIDATE_JOURNEY = "VALIDATE_JOURNEY";
export const UPDATE_SELECTED_VEHICLE_STATE = "UPDATE_SELECTED_VEHICLE_STATE";

export const FALCON_FOUND = "FALCON_FOUND";

export const RESET = "RESET";

export const UPDATE_TOTAL_JOURNEY_TIME_ON_VEHICLE_SELECT = "UPDATE_TOTAL_JOURNEY_TIME_ON_VEHICLE_SELECT";
export const UPDATE_TOTAL_JOURNEY_TIME_ON_PLANET_SELECT = "UPDATE_TOTAL_JOURNEY_TIME_ON_PLANET_SELECT";

export const API_FETCH_ERROR = "API_FETCH_ERROR";
