export const btn = "mr-2 items-center w-auto bg-blue-500 hover:bg-blue-700 text-white font-semibold focus:outline-none focus:shadow-outline py-2 px-4 rounded-sm";
export const btn_disabled = "mr-2 items-center w-auto bg-gray-500 cursor-not-allowed text-white font-semibold focus:outline-none focus:shadow-outline py-2 px-4 rounded-sm";
export const info_text = "text-4xl text-indigo-700";
export const flex_row_center = "flex flex-row items-center justify-center";
export const flex_row_start = "flex flex-row items-center justify-start";
export const flex_col_center = "flex flex-col items-center justify-center";
export const flex_row_wrap_center = "flex flex-row flex-wrap justify-center items-center";
export const badge = "bg-blue-600 text-normal text-white font-smaller rounded-full pl-2 pb-1 w-6 h-6 mr-1 ml-1";
export const flex_row_wrap_around = "flex-row justify-around flex-wrap items-center";
